language: python
python:
- 3.6

before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

install:
- pip install -r requirements.txt
- pip install coveralls

branches:
  only:
  - master

before_script:
- "export DJANGO_SETTINGS_MODULE=config.settings.dev"

script:
- cd app
- coverage run manage.py test

after_success:
- coveralls