# Generated by Django 2.2.10 on 2020-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
