# Generated by Django 2.2.10 on 2020-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_user', models.CharField(max_length=150)),
                ('post_picture', models.ImageField(upload_to='images')),
            ],
        ),
    ]
