# Generated by Django 2.2.10 on 2020-03-01 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_user', models.CharField(max_length=150)),
                ('post_modal_target', models.CharField(blank=True, max_length=100)),
                ('post_picture', models.ImageField(upload_to='img')),
                ('post_likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
